#!/usr/bin/env bash
# Bash script that diaplays "Best School" 10 times
# on the 9th iteration displays "Best School" and "Hi" on a new line

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
